# Tensor

## Tensor Creation

In [2]:
import torch
# float variable to tensor object
x = 34.0 # float value , CPU level의 type
print( type(x) )
y = torch.tensor(x) # python object to pytorch object
print( type(y) )
y

<class 'float'>
<class 'torch.Tensor'>


tensor(34.)

In [3]:
# directly create tensor
y = torch.tensor(34.0) # 자동으로 float 인식
print( type(y) )
y

<class 'torch.Tensor'>


tensor(34.)

In [4]:
# list -> tensor
x = [1,2,3,4]
y = torch.tensor(x)
print( type(x) )
print( type(y) )
y

<class 'list'>
<class 'torch.Tensor'>


tensor([1, 2, 3, 4])

In [5]:
# list of list -> tensor
x = [ [1,2,3,4],
      [5,6,7,8]
    ] # 2 dimensional array
print( torch.tensor(x) )
print( torch.tensor(x).shape )
print( torch.tensor(x).size() )

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
torch.Size([2, 4])
torch.Size([2, 4])


# Numpy object to Tensor

In [6]:
import numpy as np

a = 34.3
b = torch.tensor(a)
print(b)
print(b.dtype)

x = np.array( 34.3 )
print(type(x))
print(x.dtype)
y = torch.tensor(x)
y

# numpy로 데이터를 만들면, 데이터의 타입이 결정되며, numpy를 torch.tensor 형태로 넘겨서 torch.tensor 형태의 object도 numpy의 것으로 자동으로 결정이 됨.

tensor(34.3000)
torch.float32
<class 'numpy.ndarray'>
float64


tensor(34.3000, dtype=torch.float64)

In [7]:
x = np.array( [
                [1,2,3,4],
                [5,6,7,8]
                          ]) # 2 dimensional array
print(x.shape)
print( torch.tensor(x) )
print( torch.tensor(x).shape )
# numpy가 integer type으로 추측을 하여 아래와 같이 출력에도 나오는 것을 확인할 수 있다.

(2, 4)
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
torch.Size([2, 4])


In [8]:
x = np.array([ [
                  [
                    [1,2,3,4],
                    [5,6,7,8]
                  ]
                ]
              ]
             )
print( torch.tensor(x) )
print( torch.tensor(x).shape )


tensor([[[[1, 2, 3, 4],
          [5, 6, 7, 8]]]])
torch.Size([1, 1, 2, 4])


# Tensor daya type

- 거의 모두 지원
- tensor.dtype

In [9]:
# by creation
x = torch.tensor( [1,2,3,4], dtype=torch.float)
print( x )
print( x.dtype)

# integer 임에도 float으로 정의

tensor([1., 2., 3., 4.])
torch.float32


In [10]:
# by creation
x = torch.tensor( [1,2,3,4], dtype=torch.float16)
print( x )
print( x.dtype)

tensor([1., 2., 3., 4.], dtype=torch.float16)
torch.float16


In [11]:
# by explicit conversion by .to()

x = torch.tensor( [1,2,3,4], dtype=torch.float)
print( x )
print( x.dtype )
y = x.to(torch.int) # .to() is quite useful function in many cases. it is not for only type conversion but also other things.
print( y )
print( y.dtype )

tensor([1., 2., 3., 4.])
torch.float32
tensor([1, 2, 3, 4], dtype=torch.int32)
torch.int32


In [12]:
# by explicit conversion by .to()

x = torch.tensor( [1,2,3,4], dtype=torch.float)
print( x )
print( x.dtype )
y = x.type(torch.int)
print( y )
print( y.dtype )

tensor([1., 2., 3., 4.])
torch.float32
tensor([1, 2, 3, 4], dtype=torch.int32)
torch.int32


In [13]:
# you can even specify the type with "string" not object
x = torch.tensor( [1,2,3,4], dtype=torch.float)
print( x )
print( x.dtype )
OUR_TYPE = "torch.ShortTensor"
y = x.type(OUR_TYPE) # <- string !!
print( y )
print( y.dtype )

tensor([1., 2., 3., 4.])
torch.float32
tensor([1, 2, 3, 4], dtype=torch.int16)
torch.int16


# Tensor Shape

- Tensor is a n-dimensional array. Therefore, check and set the shape of tensor are fundamental and cruical operations for handing tensor.
- Shape operation might be your best and useful tool for deep learning.

* In here, we will check elementary shape operations.
* Some of the advanced topics will be convered in the later of this lecture.
    - Check shape
    - Reshape

In [14]:
# check shape
x = torch.tensor([
                        [1,2,3],
                        [4,5,6]
                ])
print(x)
print(x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [15]:
# you can also get values of each dimension

batch_size, dim_1 = x.shape
print( "batch size : ", batch_size)
print( "1st dimension : ", dim_1)

print(x.size()) # tensor로 출력도 가능.

batch size :  2
1st dimension :  3
torch.Size([2, 3])


In [16]:
# by "RESHAPE", you can change tensor shape whatever you want.

print("Original : ", x.shape)
print("Reshaped : ", x.reshape([3,2]).shape) # <-- check the result
print("Reshaped : ", x.reshape([1,6]).shape) # <-- check the result
print("Reshaped : ", x.reshape([6,1]).shape) # <-- check the result

print(x)
print("-----")
print(x.reshape([6]))

# data의 전체 개수가 같다면 shape 바꾸기 가능.

Original :  torch.Size([2, 3])
Reshaped :  torch.Size([3, 2])
Reshaped :  torch.Size([1, 6])
Reshaped :  torch.Size([6, 1])
tensor([[1, 2, 3],
        [4, 5, 6]])
-----
tensor([1, 2, 3, 4, 5, 6])


In [17]:
# but reshape is only allowed when the total size is same.
print("Original : ", x.shape)
print("Reshaped L ", x.reshape([6,1]).shape)

Original :  torch.Size([2, 3])
Reshaped L  torch.Size([6, 1])


## (ADVANCED) reshape and view

Pytorch support 'view' function for shaping operation.

The functionality is almost same as reshape, but the memory usage is different.

In [18]:
# data 자체의 memory 구조를 바꿔주는 것이 아닌, data를 access할 때의 shape를 바꿔준다.

x = torch.randn(4, 4)
print("x :", x.size())
y = x.view(16)
print('y :', y.size())
z = x.view(-1,8) # the size -1 is inferred from other dimensions // 알아서 추측한다.
print("z :", z.size())

x : torch.Size([4, 4])
y : torch.Size([16])
z : torch.Size([2, 8])


View is a just mirror if data with another shape.

So, it does not change data is self.

In [19]:
a = torch.tensor( [
    
                        [
                            [1, 2, 3, 4],
                            [5, 6, 7, 8]
                        ],
                        [
                            [11, 12, 13, 14],
                            [15, 16, 17, 18]
                        ],
                        [
                            [21, 22, 23, 24],
                            [25, 26, 27, 28]
                        ]
])
print(a)
print("a : ", a.size())
b = a.view(3,4,2) # change shape
print(b)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[11, 12, 13, 14],
         [15, 16, 17, 18]],

        [[21, 22, 23, 24],
         [25, 26, 27, 28]]])
a :  torch.Size([3, 2, 4])
tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8]],

        [[11, 12],
         [13, 14],
         [15, 16],
         [17, 18]],

        [[21, 22],
         [23, 24],
         [25, 26],
         [27, 28]]])


In [20]:
a = torch.tensor( [
    
                        [
                            [1, 2, 3, 4],
                            [5, 6, 7, 8]
                        ],
                        [
                            [11, 12, 13, 14],
                            [15, 16, 17, 18]
                        ],
                        [
                            [21, 22, 23, 24],
                            [25, 26, 27, 28]
                        ]
])
print(a)
print(a[1])
b = a.view(3,4,2) # change shape
print("[before change]")
print("b :", b)
print("------------------")
a[1] = torch.tensor( [[51,52,53,54],
                      [55,56,57,58]]) # < -- assign new value
print(a)
print("[after change]")
print("b :", b)

# b에 대해 작업하지 않았지만, b의 내부 data가 바뀌었다.
# view는 shape를 바꿔서 바라만 보고 있는 것이다.

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[11, 12, 13, 14],
         [15, 16, 17, 18]],

        [[21, 22, 23, 24],
         [25, 26, 27, 28]]])
tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])
[before change]
b : tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8]],

        [[11, 12],
         [13, 14],
         [15, 16],
         [17, 18]],

        [[21, 22],
         [23, 24],
         [25, 26],
         [27, 28]]])
------------------
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[51, 52, 53, 54],
         [55, 56, 57, 58]],

        [[21, 22, 23, 24],
         [25, 26, 27, 28]]])
[after change]
b : tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8]],

        [[51, 52],
         [53, 54],
         [55, 56],
         [57, 58]],

        [[21, 22],
         [23, 24],
         [25, 26],
         [27, 28]]])


In [21]:
print(b)

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8]],

        [[51, 52],
         [53, 54],
         [55, 56],
         [57, 58]],

        [[21, 22],
         [23, 24],
         [25, 26],
         [27, 28]]])


In [22]:
b[1] = torch.tensor([[152,152],
                     [153,154],
                     [155,156],
                     [157,158]])
print(a)

# 실제 안으로 들어가서 값을 바꾸기 때문에 a를 출력해도 바뀌는 걸 확인 가능.

tensor([[[  1,   2,   3,   4],
         [  5,   6,   7,   8]],

        [[152, 152, 153, 154],
         [155, 156, 157, 158]],

        [[ 21,  22,  23,  24],
         [ 25,  26,  27,  28]]])


# Tensor Device Change

Pytorch support GPU calculation.

We can transfer data in CPU to GPU or vice versa.
- CPU to GPU
- GPU to CPU

**NOTE** You need 'GPU' to run the following section

google -- colab

In [23]:
# CPU to GPU @ creation
a = torch.tensor([1,2,3,4], device="cuda:0") # 어떤 GPU memory에 이 tensor를 올릴 것인가에 대한 명시이다. 숫자는 n번째 GPU를 의미한다.
print(a)
print(a.device)
b = torch.tensor([1,2,3,4], device='cpu')
print(b)
print(b.device)
c = torch.tensor([1,2,3,4]) # < -- default device : cpu
print(c)
print(c.device)

tensor([1, 2, 3, 4], device='cuda:0')
cuda:0
tensor([1, 2, 3, 4])
cpu
tensor([1, 2, 3, 4])
cpu


In [24]:
# CPU to GPU @ after creation
a = torch.tensor([1,2,3,4])
print(a)
print(a.device)
b = a.to('cuda') #. --- .to(~~~)
print(b)
print(b.device)
print("---------try to change b---------")
b[3] = 14
print("a :",a)
print("b :",b)

tensor([1, 2, 3, 4])
cpu
tensor([1, 2, 3, 4], device='cuda:0')
cuda:0
---------try to change b---------
a : tensor([1, 2, 3, 4])
b : tensor([ 1,  2,  3, 14], device='cuda:0')


# Tensor @ GPU data to CPU data

We need some operations to fetch GPU data to CPU area.

- GPU data to CPU
  - torch.tensor @GPU --> torch.tensor @CPU --> python object @CPU
  - torch.tensor @GPU --> torch.tensor @CPU --> numpy object @CPU

In [25]:
a = torch.tensor( [
    
                        [
                            [1, 2, 3, 4],
                            [5, 6, 7, 8]
                        ],
                        [
                            [11, 12, 13, 14],
                            [15, 16, 17, 18]
                        ],
                        [
                            [21, 22, 23, 24],
                            [25, 26, 27, 28]
                        ]
]).to('cuda') # <- GPU
print(a)
print(a.device)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[11, 12, 13, 14],
         [15, 16, 17, 18]],

        [[21, 22, 23, 24],
         [25, 26, 27, 28]]], device='cuda:0')
cuda:0


In [26]:
b = a.cpu() # a가 cpu level로 내려와서 나의 cpu에 저장됨.
print(b)
print(type(b))
print(b.device)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[11, 12, 13, 14],
         [15, 16, 17, 18]],

        [[21, 22, 23, 24],
         [25, 26, 27, 28]]])
<class 'torch.Tensor'>
cpu


In [27]:
c = b.tolist()
print(c)
print(type(c))

[[[1, 2, 3, 4], [5, 6, 7, 8]], [[11, 12, 13, 14], [15, 16, 17, 18]], [[21, 22, 23, 24], [25, 26, 27, 28]]]
<class 'list'>


In [28]:
c = b.numpy()
print(c)
print(type(c))

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]

 [[21 22 23 24]
  [25 26 27 28]]]
<class 'numpy.ndarray'>


In [29]:
# a.numpy()

# Error, numpy()라는 format은 cpu만 support하는 것이므로, GPU에 담기는 메모리를 numpy로 하면 작동이 되지 않음.

In [30]:
a.cpu().numpy()
print(a)
print(type(a.cpu().numpy()))

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[11, 12, 13, 14],
         [15, 16, 17, 18]],

        [[21, 22, 23, 24],
         [25, 26, 27, 28]]], device='cuda:0')
<class 'numpy.ndarray'>


When we want to get scalar value directly, there is item() function.

In [31]:
a = torch.tensor([1,2,3,4], device='cuda')
print(a)
print(a.device)

tensor([1, 2, 3, 4], device='cuda:0')
cuda:0


In [32]:
# a.item() # it will cause ERROR - since item() support only scalars

In [33]:
a = torch.tensor([1], device='cuda')
print(a)
print(a.device)
print("-----")
b = a.item() # scalar 값일 때 가능.
print(b)
print(type(b))

tensor([1], device='cuda:0')
cuda:0
-----
1
<class 'int'>


In [34]:
a = torch.tensor(101.3434, device='cuda')
print(a)
print(a.device)
print('-----')
b = a.item()
print(b)
print(type(b))

tensor(101.3434, device='cuda:0')
cuda:0
-----
101.34339904785156
<class 'float'>


# 1 to N Operations

In [35]:
a = torch.tensor( [
    
                        [
                            [1, 2, 3, 4],
                            [5, 6, 7, 8]
                        ],
                        [
                            [11, 12, 13, 14],
                            [15, 16, 17, 18]
                        ],
                        [
                            [21, 22, 23, 24],
                            [25, 26, 27, 28]
                        ]
])
print(a)
print(a.shape)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[11, 12, 13, 14],
         [15, 16, 17, 18]],

        [[21, 22, 23, 24],
         [25, 26, 27, 28]]])
torch.Size([3, 2, 4])


# Let's split the data with 3 parts

In [36]:
a_l_tensors = torch.chunk(a, chunks=3, dim=0)
print(a_l_tensors)
print(a_l_tensors[0])
print("-----")
print(a_l_tensors[0].shape)
print(a_l_tensors[1].shape)
print(a_l_tensors[2].shape)

(tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]]), tensor([[[11, 12, 13, 14],
         [15, 16, 17, 18]]]), tensor([[[21, 22, 23, 24],
         [25, 26, 27, 28]]]))
tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]])
-----
torch.Size([1, 2, 4])
torch.Size([1, 2, 4])
torch.Size([1, 2, 4])


In [40]:
print(torch.chunk(a, chunks=4, dim=-1))
print(torch.chunk(a, chunks=4, dim=-1)[1])
print("-----")
print(torch.chunk(a, chunks=4, dim=-1)[0].shape)
print(torch.chunk(a, chunks=4, dim=-1)[1].shape)
print(torch.chunk(a, chunks=4, dim=-1)[2].shape)
print(torch.chunk(a, chunks=4, dim=-1)[3].shape)

(tensor([[[ 1],
         [ 5]],

        [[11],
         [15]],

        [[21],
         [25]]]), tensor([[[ 2],
         [ 6]],

        [[12],
         [16]],

        [[22],
         [26]]]), tensor([[[ 3],
         [ 7]],

        [[13],
         [17]],

        [[23],
         [27]]]), tensor([[[ 4],
         [ 8]],

        [[14],
         [18]],

        [[24],
         [28]]]))
tensor([[[ 2],
         [ 6]],

        [[12],
         [16]],

        [[22],
         [26]]])
-----
torch.Size([3, 2, 1])
torch.Size([3, 2, 1])
torch.Size([3, 2, 1])
torch.Size([3, 2, 1])


# N to 1 Operations

In [42]:
# by cat

print(a_l_tensors)
print(a_l_tensors[0].shape)
print(a_l_tensors[1].shape)
print(a_l_tensors[2].shape)

(tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]]), tensor([[[11, 12, 13, 14],
         [15, 16, 17, 18]]]), tensor([[[21, 22, 23, 24],
         [25, 26, 27, 28]]]))
torch.Size([1, 2, 4])
torch.Size([1, 2, 4])
torch.Size([1, 2, 4])


In [45]:
b = torch.cat(a_l_tensors)
print(b)
print(b.shape)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[11, 12, 13, 14],
         [15, 16, 17, 18]],

        [[21, 22, 23, 24],
         [25, 26, 27, 28]]])
torch.Size([3, 2, 4])


In [46]:
# but you can concatenate in different ways
c = torch.cat(a_l_tensors, dim=1)
print(c)
print(c.shape)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [11, 12, 13, 14],
         [15, 16, 17, 18],
         [21, 22, 23, 24],
         [25, 26, 27, 28]]])
torch.Size([1, 6, 4])


In [47]:
# but you can concatenate in different ways
c = torch.cat(a_l_tensors, dim=-1)
print(c)
print(c.shape)

tensor([[[ 1,  2,  3,  4, 11, 12, 13, 14, 21, 22, 23, 24],
         [ 5,  6,  7,  8, 15, 16, 17, 18, 25, 26, 27, 28]]])
torch.Size([1, 2, 12])


# Torch.STACK

- Concatenates a sequence of tensors along a new dimension.
- All tensors need to be of the same size.

In [48]:
print("original shape of a", a.shape)
print(a_l_tensors)
# tuple의 모음
print("-----")
e = torch.stack(a_l_tensors)
print(e)
print(e.shape)

original shape of a torch.Size([3, 2, 4])
(tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]]), tensor([[[11, 12, 13, 14],
         [15, 16, 17, 18]]]), tensor([[[21, 22, 23, 24],
         [25, 26, 27, 28]]]))
-----
tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8]]],


        [[[11, 12, 13, 14],
          [15, 16, 17, 18]]],


        [[[21, 22, 23, 24],
          [25, 26, 27, 28]]]])
torch.Size([3, 1, 2, 4])


In [49]:
a = torch.tensor( [
    
                        [
                            [1, 2, 3, 4],
                            [5, 6, 7, 8]
                        ],
                        [
                            [11, 12, 13, 14],
                            [15, 16, 17, 18]
                        ],
                        [
                            [21, 22, 23, 24],
                            [25, 26, 27, 28]
                        ]
])
print(a)
print(a.shape)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[11, 12, 13, 14],
         [15, 16, 17, 18]],

        [[21, 22, 23, 24],
         [25, 26, 27, 28]]])
torch.Size([3, 2, 4])


In [50]:
print(a.shape)
b = torch.transpose(a, 0, 1)
print(b.shape)
print(b)

torch.Size([3, 2, 4])
torch.Size([2, 3, 4])
tensor([[[ 1,  2,  3,  4],
         [11, 12, 13, 14],
         [21, 22, 23, 24]],

        [[ 5,  6,  7,  8],
         [15, 16, 17, 18],
         [25, 26, 27, 28]]])


In [51]:
print(a.shape)
c = torch.transpose(a, 0, -1)
print(c.shape)
print(c)

torch.Size([3, 2, 4])
torch.Size([4, 2, 3])
tensor([[[ 1, 11, 21],
         [ 5, 15, 25]],

        [[ 2, 12, 22],
         [ 6, 16, 26]],

        [[ 3, 13, 23],
         [ 7, 17, 27]],

        [[ 4, 14, 24],
         [ 8, 18, 28]]])


In [52]:
print("original shape of a", a.shape)
d = a.permute(2,0,1)
print(d.shape)
print(d)

original shape of a torch.Size([3, 2, 4])
torch.Size([4, 3, 2])
tensor([[[ 1,  5],
         [11, 15],
         [21, 25]],

        [[ 2,  6],
         [12, 16],
         [22, 26]],

        [[ 3,  7],
         [13, 17],
         [23, 27]],

        [[ 4,  8],
         [14, 18],
         [24, 28]]])


# Squeeze

In [53]:
x = torch.zeros(2,1,2,1,2)
print(x.shape)

torch.Size([2, 1, 2, 1, 2])


In [55]:
y = torch.squeeze(x)
print(y.shape) # <-- you will seee 1 is removed

torch.Size([2, 2, 2])


In [58]:
# or you can specify the squeezing dimension
y = torch.squeeze(x, 1)
print(y.shape) # < - you will see dim=1 is removed

torch.Size([2, 2, 1, 2])


# Unsqueeze

In [60]:
print(y.shape)
z = y.unsqueeze(dim=1)
print(z.shape)

torch.Size([2, 2, 1, 2])
torch.Size([2, 1, 2, 1, 2])


# Tensor indexing

In [62]:
x = [ [0,1,2,3,4,5,6,7,8,9,],
     [10,11,12,13,14,15,16,17,18,19],
     [20,21,22,23,24,25,26,27,28,29],
     [30,31,32,33,34,35,36,37,38,39]]
x = torch.tensor(x)
x

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [63]:
x[:,3]

tensor([ 3, 13, 23, 33])

In [64]:
x[3,:]

tensor([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [65]:
x[:,2:5]

tensor([[ 2,  3,  4],
        [12, 13, 14],
        [22, 23, 24],
        [32, 33, 34]])

In [66]:
# -1

x[:,-1]

tensor([ 9, 19, 29, 39])

In [67]:
x[-1,:]

tensor([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [68]:
# Somtimes, you can just index the element - what you want

In [70]:
x = [ [0,1,2,3,4,5,6,7,8,9,],
     [10,11,12,13,14,15,16,17,18,19],
     [20,21,22,23,24,25,26,27,28,29],
     [30,31,32,33,34,35,36,37,38,39]]
x = torch.tensor(x)
print(x.shape)
indices = torch.LongTensor([3,7,1,4])
print(x)
print("---")
x[:,indices]

torch.Size([4, 10])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])
---


tensor([[ 3,  7,  1,  4],
        [13, 17, 11, 14],
        [23, 27, 21, 24],
        [33, 37, 31, 34]])

# Reduce Operations

- min, max, mean
- argmax, argmin

In [71]:
a = torch.tensor( [
    
                        [
                            [1, 2, 3, 4],
                            [5, 6, 7, 8]
                        ],
                        [
                            [11, 12, 13, 14],
                            [15, 16, 17, 18]
                        ],
                        [
                            [21, 22, 23, 24],
                            [25, 26, 27, 28]
                        ]
])
print(a)
print(a.shape)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[11, 12, 13, 14],
         [15, 16, 17, 18]],

        [[21, 22, 23, 24],
         [25, 26, 27, 28]]])
torch.Size([3, 2, 4])


In [72]:
torch.max(a)

tensor(28)

In [73]:
torch.max(a, dim=2)

torch.return_types.max(
values=tensor([[ 4,  8],
        [14, 18],
        [24, 28]]),
indices=tensor([[3, 3],
        [3, 3],
        [3, 3]]))

In [74]:
m = torch.max(a, dim=1)
print(m) # note that .max() return tuple
print("shpae : ", m.values.shape)

torch.return_types.max(
values=tensor([[ 5,  6,  7,  8],
        [15, 16, 17, 18],
        [25, 26, 27, 28]]),
indices=tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]))
shpae :  torch.Size([3, 4])


argmax and argmin get indices of max or min directly

In [75]:
torch.argmax(a, dim=2)

tensor([[3, 3],
        [3, 3],
        [3, 3]])