In [1]:
# 다차원 텐서 표현
import torch

# 0D Tensor
# 하나의 숫자를 담고 있는 텐서
# 축과 형상 없음
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [4]:
# 1D Tensor ( == vector)
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [5]:
# 2D Tensor ( == matrix)
t2 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [10]:
# 3D Tensor ( == cube)
# 데이터가 연속된 시퀀스 데이터나 시간 축이 포함된 시계열 데이터에 해당
# samples, timesteps, features를 가진 구조로 사용
t3 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [11]:
# 4D Tensor
# 컬러 이미지 데이터가 대표적인 사례, 흑백은 3D tensor로 가능.
# samples, heights, width, channel 을 가진 구조로 사용


In [12]:
# 5D Tensor
# 비디오 데이터가 대표적인 사례
# samples, frames(ex. 초당 30개의 프레임), heights, width, channel 을 가진 구조로 사용


In [24]:
# 텐서의 연산
# Operations

import math

a = torch.rand(1,2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5)) # 최대 최소를 제한한다.

tensor([[-0.7923,  0.5464]])
tensor([[0.7923, 0.5464]])
tensor([[-0., 1.]])
tensor([[-1.,  0.]])
tensor([[-0.5000,  0.5000]])


In [27]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a)) # 표준편차
print(torch.prod(a)) # 곱
print(torch.unique(torch.tensor([1,2,3,1,2,2]))) # 중복제거

tensor([[-0.7923,  0.5464]])
tensor(-0.7923)
tensor(0.5464)
tensor(-0.1230)
tensor(0.9466)
tensor(-0.4329)
tensor([1, 2, 3])


In [28]:
x = torch.rand(2,2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))
print(x.min(dim=0))
print(x.min(dim=1))

tensor([[0.6353, 0.0157],
        [0.3835, 0.2977]])
torch.return_types.max(
values=tensor([0.6353, 0.2977]),
indices=tensor([0, 1]))
torch.return_types.max(
values=tensor([0.6353, 0.3835]),
indices=tensor([0, 0]))


In [29]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

tensor([[0.7536, 0.9204],
        [0.2311, 0.2216]])
tensor([[0.1339, 0.2691],
        [0.1463, 0.8330]])


In [32]:
print(x+y)
print(torch.add(x,y))

tensor([[0.8875, 1.1895],
        [0.3774, 1.0546]])
tensor([[0.8875, 1.1895],
        [0.3774, 1.0546]])


In [33]:
result = torch.empty(2,4)
torch.add(x,y,out=result)
print(result)

tensor([[0.8875, 1.1895],
        [0.3774, 1.0546]])


/var/folders/tb/y4nqb45d7y7bdblsw13wgbd00000gn/T/ipykernel_88083/7703770.py:2: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /Users/distiller/project/conda/conda-bld/pytorch_1634272478997/work/aten/src/ATen/native/Resize.cpp:23.)
  torch.add(x,y,out=result)
