In [27]:
# version
import torch
torch.__version__

'1.10.0'

In [3]:
# 초기화 되지 않은 텐서
x = torch.empty(4,2)
print(x)

tensor([[2.9575e+02, 4.5852e-41],
        [2.9575e+02, 4.5852e-41],
        [2.9707e+02, 4.5852e-41],
        [2.9707e+02, 4.5852e-41]])


In [5]:
# 무작위로 초기화 된 텐서
# random 기준 초기화.
x = torch.rand(4,2)
print(x)

tensor([[0.3227, 0.4494],
        [0.9004, 0.8716],
        [0.0577, 0.0663],
        [0.6075, 0.3949]])


In [6]:
# 데이터 타입이 long, 0으로 채우기
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [8]:
# 입력 값 초기화
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [11]:
# 2 x 4 for double type, all 1
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [12]:
# x와 같지만 float type
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[-0.2387, -0.5292, -0.2734,  0.8276],
        [ 0.2818,  0.6912,  1.9315,  1.4032]])


In [13]:
# size
print(x.size())

torch.Size([2, 4])


In [14]:
# data type
ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [18]:
# type casting
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [19]:
it = torch.IntTensor([1,2,3])
print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [21]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


In [22]:
# CUDA Tensor
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.1297])
0.12967686355113983
torch.float32


In [26]:
# GPU run time에 연결되어 있어서 가능하다면 cuda, 아니라면 cpu.
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y = torch.ones_like(x, device=device)
print(y)
print(x.to(device))
print(x)
z = x + y
print(z)
print(z.to('cpu', torch.double))

cpu
tensor([1.])
tensor([0.1297])
tensor([0.1297])
tensor([1.1297])
tensor([1.1297], dtype=torch.float64)
