In [3]:
import torch
# autograd : 자동 미분 기능
# 코드를 어떻게 작성하냐에 따라 역전파가 정의된다는 뜻.
# requires_grad 속성을 True로 설정하면 해당 텐서에서 이루어지는 모든 연산을 추적하기 시작함.
# 기록 추적을 중단하려면 .detach()를 호출하여 연산기록으로부터 분리

a = torch.rand(3,3)
a *= 3
print(a)
print(a.requires_grad)

a.requires_grad_(True)
print(a.requires_grad)

b = (a * a).sum()
print(b) # 어떤 연산에 의해 이루어졌는지 grad_fn으로 기록에 남김.
print(b.grad_fn)

tensor([[0.5296, 2.7405, 0.8784],
        [0.1453, 0.2156, 0.8055],
        [2.9123, 1.8810, 0.8887]])
False
True
tensor(22.0883, grad_fn=<SumBackward0>)


In [4]:
x = torch.ones(3,3, requires_grad = True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [5]:
y = x + 5
print(y)

z = y * y
out = z.mean()
print(z,out)
print(out)
out.backward()

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)
tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<MulBackward0>) tensor(36., grad_fn=<MeanBackward0>)
tensor(36., grad_fn=<MeanBackward0>)


In [6]:
# grad로 실제 미분값 봄
print(x)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])


In [7]:
x = torch.randn(3, requires_grad = True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

# 신경망은 tensor로 이루어진 layer들을 각각 계산하다가 최종적으로 backpropagation하는 형태.

tensor([1069.6057, -474.7892,   90.1422], grad_fn=<MulBackward0>)


In [9]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)
print(x.grad)

# v 기준으로 backward가 이루어짐.

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [10]:
# with torch.no_grad() 를 통해 기울기의 업데이트를 하지 않을 수 있다.
# 기록을 추적당하는 것을 방지하기 위해 코드 블럭을 with torch.no_grad로 감싸면 기울기 계산을 필요없지만,
# requires_grad = True 로 설정되어 있어 학습 가능한 매개변수를 갖는 모델을 평가할 때 유용하다.
# 모델 평가 시, 모델을 Update하지 않으니, 기울기를 계산하지 않고 평가만 진행. 그렇다면 no_grad 필요.

print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)
    # 안에서는 requires_grad가 false가 나옴을 알 수 있디.

True
True
False


In [11]:
# 내용물은 같지만, requires_grad가 다른 새로운 Tensor를 가지고 올 때.
# detach()
print(x.requires_grad)
y = x.detach() # detach로 값 False로 바꾼다.
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


In [12]:
# backward)를 통해 grad값 계산
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [13]:
a = torch.ones(2, 2, requires_grad=True)
print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [20]:
print(a.data)
print(a.grad)
print(a.grad_fn)

# tensor에 대한 연산 들어간 것 없음. 그저 초기화된 상태.
# 계산된 것이 없으므로.

tensor([[1., 1.],
        [1., 1.]])
None
None


In [24]:
b = a + 2
print(b)
# add 연산 저장

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [25]:
c = b ** 2
print(c)
# power backward 기록 남음

tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)


In [32]:
out = c.sum()
print(out)
# sum backward

tensor(36., grad_fn=<SumBackward0>)


In [33]:
print(out)
out.backward()

tensor(36., grad_fn=<SumBackward0>)


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [37]:
print(a.data)
print(a.grad)
print(a.grad_fn)

# tensor a는 직접 계산한 것은 없고 활용만 함.
# 반영한 것은 없기 때문에 fn은 None이 나옴.

tensor([[1., 1.],
        [1., 1.]])
tensor([[6., 6.],
        [6., 6.]])
None


In [38]:
print(b.data)
print(b.grad)
print(b.grad_fn)

tensor([[3., 3.],
        [3., 3.]])
None


In [39]:
print(c.data)
print(c.grad)
print(c.grad_fn)

tensor([[9., 9.],
        [9., 9.]])
None


In [40]:
print(out.data)
print(out.grad)
print(out.grad_fn)

tensor(36.)
None
